apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: web
        image: registry.hub.docker.com/minamaher/my-app:1.0.0 # {"$imagepolicy": "flux-system:my-app-policy"}
        ports:
        - containerPort: 8080
