apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps
  prune: true
  wait: true             # Instructs Flux to wait for resources to become Ready
  timeout: 2m            # Max time to wait before marking the deployment as failed
